### PR TITLE
Bugfix issue #2

### LINKED ISSUE #2: Doesn't work with visual block selection
Can't find text with shift+V visual block selections. Returns 0 lines or sometimes an error

### PR DESCRIPTION
**Pull request by Zonric**
Fix issue #2 and sub-issues described in [my reply](https://github.com/Zonric/codecopy.nvim/issues/2#issuecomment-2953287558), along with an over-cutting shorter lines causing misalignment.

### CODE REVIEW

File: lua/codecopy/visualselection.lua [hunk 1]
```diff
@@ -4,26 +4,84 @@ local options = require("codecopy.config").options
...
+			-- Padding for lines over-cut by the slice
+			if linelength < end_pos[3] then
+				lines[i] = lines[i] .. string.rep(" ", end_pos[3] - linelength)
+			end
+			-- Time for the trim...
+			lines[i] = string.sub(lines[i], start_pos[3], end_pos[3])
+		end
+	end
+	linecount = #lines
+	-- Debug output
```
Comment (williamrice) [inline lua/codecopy/visualselection.lua:82]: hey you should do this because of this. can you check it out

Comment (Zonric) [reply lua/codecopy/visualselection.lua:82]: This is what that will be when it is this.

**Review by williamrice — APPROVED** [review]
